### PR TITLE
Changing RCTBridge import to React namespace per RN 0.40 update

### PR DESCRIPTION
**Pull request by isaacnass**
In React Native 0.40 everyone is getting duplicate class errors, this fixes those 👍

### CODE REVIEW

**Comment by johanblomgren** [comment]
Awaiting the merge of this PR. 0.40 should be fairly established by now.

**Comment by stephanedemotte** [comment]
@isaacnass push ?

**Comment by isaacnass** [comment]
@stephanedemotte Push what? I am lé open source n00b I have no idea what I'm doing 😛

**Comment by johanblomgren** [comment]
It's @pwmckenna who needs to accept or dismiss this PR.

**Comment by stephanedemotte** [comment]
@isaacnass  hihi, same here 💃 
So @pwmckenna acceeeeept and bump it up ! ;)

**Comment by MaxMillington** [comment]
+1. Please merge this

**Comment by peterept** [comment]
Yes, please merge. Took me ages to figure this out also, and only then saw this PR. I will add an issue

**Comment by armenr** [comment]
+1. Had to figure this out manually over the course of a full day. Would be a major help :)

**Comment by pwmckenna** [comment]
@isaacnass just added you as a contributor to this project and will be giving you npm access as well. Sorry for the delay, and thanks for the contribution. 👍 

Mind sending me your npm username?

**Comment by wewark** [comment]
Why hasn't this been merged yet? I had to copy the whole project out of `node_modules` to make these exact changes.

**Comment by pwmckenna** [comment]
@wewark I haven't merged it because I don't have time to verify that this is a good patch. If you're interested I'd be happy to give you access to both this repo and npm so you can publish updates.

**Comment by pwmckenna** [comment]
@isaacnass thanks for the pr. I didn't have time to verify this, but there was enough demand that I merged and published as 0.0.7. If there are any more pressing issues, I'm happy to hand out write access so I'm not a bottleneck.

**Pull request merged**
