### PR TITLE
Convert into packaged component

### PR DESCRIPTION
**Pull request by brentvatne**
Here you go @pwmckenna! Blog post here: http://brentvatne.ca/packaging-react-native-component/

When you pull it, you can publish the module to npm then `npm install` in the example project and it should work. I tested it from just manually copying and pasting into the node_modules directory and it seems to work fine. Let me know if you run into any issues!

### CODE REVIEW

**Comment by pwmckenna** [comment]
Thank you! This looks amazing. I'll merge it in and test, then publish.

**Comment by brentvatne** [comment]
:rocket:

**Comment by pwmckenna** [comment]
er, so i don't know how i didn't realize this when i was manually moving the files, but the .h/.m files are getting git ignored. were they just git mv-ed to RNMotionManager/ ?

**Comment by brentvatne** [comment]
@pwmckenna - check out #2

**Pull request merged**
